### ISSUE TITLE
Doubt:- how is api getting called

### ISSUE THREAD

**Issue by Biki-das** [btholt/complete-intro-to-react-v8#12]
i am currently trying to understand something which i am just not getting, so we called the pet api in our pets app,

```
 async function requestPets() {
    const res = await fetch(`http://pets-v2.dev-apis.com/pets?animal=${animal}&location=${location}&breed=${breed}`
   
    );
    const json = await res.json();
    setPets(json.pets);

```
how we are able to preload the api data using the useEffect, as during preload we are not passing the animal location and breed so how we are getting the data

**Comment by J-Filip** [comment]
If I am not mistaken, we are sending empty strings for this variables (animal, location, breed) which returns all the animals.

You can check it out in dev tools under "Network" tab.

**Comment by florentdrousset** [comment]
Well, I'm a little late but you can try it youself : if you navigate to https://pets-v2.dev-apis.com/pets or pass the parameters animal, location and breed without no value, the API will return all animals in any case.
