### ISSUE TITLE
React Router link is throwing Error 404.

### ISSUE THREAD

**Issue by dapoadedire** [btholt/complete-intro-to-react-v8#54]
The link here is throwing an error.

https://github.com/btholt/complete-intro-to-react-v8/blob/main/lessons/05-react-capabilities/A-react-router.md#:~:text=If%20you%27re%20upset%20about%20the%20element%20prop%20vs%20children%2C%20read%20their%20rationale%20here

![image](https://user-images.githubusercontent.com/95668340/210316939-42357823-e404-4fe3-9ccb-bb65e07f7cfc.png)

**Comment by dtauer** [comment]
Thanks for catching this. Here's the correct link: https://reactrouter.com/en/6.6.1/upgrading/v5#advantages-of-route-element
