### ISSUE TITLE
Cannot connect to localhost after Vite config setup

### ISSUE THREAD

**Issue by samuelksmith** [btholt/complete-intro-to-react-v8#79]
When I run NPM run dev in my terminal it looks correct and seems like the server is running but when I navigate to http://localhost:5173/ I can't connect.

<img width="1247" alt="CleanShot 2023-06-01 at 17 53 04@2x" src="https://github.com/btholt/complete-intro-to-react-v8/assets/127219445/6e2e6c2b-867f-4e58-9ff9-7fcfc8f7a3b5">

<img width="451" alt="CleanShot 2023-06-01 at 17 54 08@2x" src="https://github.com/btholt/complete-intro-to-react-v8/assets/127219445/a427559e-9a3f-429b-88d9-47ba4f9f6cbb">

This is during the Vite Setup video.

**Comment by vbenedeto** [comment]
Can you tell me how this was solved?
