### ISSUE TITLE
Refreshing webpage when using wsl and vite - additional config

### ISSUE THREAD

**Issue by proy01** [btholt/complete-intro-to-react-v8#82]
Hello! So, while taking the course on FrontEnd Masters, I realized that my webpage (while using Vite) was not refreshing when I made changes to my files. For example going from useState("Seattle, WA") to useState(""). On searching around a little, I noticed that with wsl (as we are using npm, which runs with wsl), changing the config file to this allows for page refresh:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  root: "src",
  server: {
    watch: {
        usePolling: true
    }
  }
});
```

I am not sure if this is the case with other PCs, but I found this useful. 
Happy learning!

**Comment by florentdrousset** [comment]
Thank you ! That's exactly what I was looking for.
