### ISSUE TITLE
Pets service requests to https://pets-v2.dev-apis.com not working. Can't run course applets that use them.

### ISSUE THREAD

**Issue by mikesae** [btholt/complete-intro-to-react-v8#86]
Requests like https://pets-v2.dev-apis.com/breeds?animal=cat are responding with 403s.

**Comment by dtauer** [comment]
Thanks for reporting. Yes, we're working on getting the API backup ASAP.

**Comment by mikesae** [comment]
Thank you @dtauer. Really enjoying the courses, both intro and intermediate react.

**Comment by mikesae** [comment]
IDK why I closed this, but it's still open.

**Comment by dtauer** [comment]
It's back up and running!
