### ISSUE TITLE
Fetch errors

### ISSUE THREAD

**Issue by TJCole03** [btholt/complete-intro-to-react-v8#88]
Hello, 

I am continuting to get this error message from my fetchSearch and fetchBreedList files: Error: pet search not okay , , 
    at Object.fetchSearch [as queryFn] (fetchSearch.jsx:13:15)

I've tried changing the 'http' in the urls to 'https' and that did not work. I also just made all my files .jsx and that didn't work either. I've been on this error for over a month now and haven't found any answers. I finished the entire lesson and got the entire code written but cannot render my pet searches. Any suggestions?

**Comment by TJCole03** [comment]
I should add that the errors come in both the fetchSearch and fetchBreedList files.

**Comment by dtauer** [comment]
@TJCole03 - Can you push up your code to a repo so I can take a look at it?

**Comment by TJCole03** [comment]
It's all in my own Repo under pet-adoption or something similar. I can just send you the link if that's okay with you?

**Comment by dtauer** [comment]
Totally forgot to get back to you on this, but it was an issue with Azure. we've fixed it so things should be good now.
